output "runner_public_ip" {
  value       = module.network.public_ip_address
  description = "Public IP address of the runner VM"
}

output "runner_ssh_private_key" {
  value       = module.compute.private_key_pem
  description = "Private SSH key generated by Terraform for the runner VM"
  sensitive   = true
}